@startuml "db"
!theme plain

entity "USER" as U {
    *user_id : UUID <<PK>>
    --
    first_name: VARCHAR(20)
    last_name: VARCHAR(20)
    email : VARCHAR(255) <<UNIQUE>>
    avatar_url: VARCHAR(300)?
    password_hash : VARCHAR(255)
    role: ENUM('CUSTOMER', 'ADMIN')
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
    deleted_at : TIMESTAMP?
}

entity "PRODUCT" as P {
    *product_id : UUID <<PK>>
    --
    name : VARCHAR(255)
    description : TEXT
    raw_price : DECIMAL(12,2)
    image_url : VARCHAR(255)
    stock_quantity : INT
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
    deleted_at : TIMESTAMP?
}

entity "PRODUCT_PROMOTIONS" as P_P {
    *promotion_id : UUID <<PK>>
    --
    product_id : UUID <<FK>>  -- ON DELETE CASCADE
    promotion_name : VARCHAR(400)
    promotion_description : VARCHAR(1000)
    promotion_type : ENUM('PERCENTAGE','FIXED')
    promotion_status : ENUM('DRAFT','RUNNING','EXPIRED','ARCHIVED')
    start_at : TIMESTAMP
    end_at : TIMESTAMP
}

entity "ORDER" as O {
    *order_id : UUID <<PK>>
    --
    user_id : UUID <<FK>>
    receiver_name : VARCHAR(100)
    phone : VARCHAR(20)
    address : VARCHAR(255)
    raw_total_amount : DECIMAL(12,2)
    final_total_amount : DECIMAL(12,2)
    created_at : TIMESTAMP
    updated_at : TIMESTAMP
}

entity "ORDER_ITEMS" as OI {
    *order_item_id : UUID <<PK>>
    order_id : UUID <<FK>>  -- ON DELETE CASCADE
    product_id : UUID <<FK>>  -- RESTRICTED
    quantity : INT
    unit_price : DECIMAL(12,2)
    promotion : DECIMAL(12,2)
    final_price : DECIMAL(12,2)
    subtotal : DECIMAL(12,2)
}

entity "ORDER_STATUS" as OS {
    *order_status_id: UUID <<PK>>
    --
    order_status_code: VARCHAR(31)
    order_status_name: VARCHAR(100)
}

entity "ORDER_STATUS_HISTORY" as OSH {
    *order_status_history_id : UUID <<PK>>
    --
    order_id : UUID <<FK>>  -- ON DELETE CASCADE
    order_status_id : UUID <<FK>>  -- RESTRICTED
    changed_at : TIMESTAMP
    changed_by : UUID?      -- SET NULL
    note : TEXT?
}

entity "ADJUSTMENT" as ADJ {
  *adjustment_id : UUID <<PK>>
  --
  order_id : UUID <<FK>>  -- ON DELETE CASCADE
  adjustment_type : ENUM('VOUCHER','FLASHSALE','COMBO','MANUAL')
  value_type : ENUM('PERCENTAGE','FIXED')
  value : DECIMAL(12,2)
  applied_amount : DECIMAL(12,2)
  reason : TEXT?
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

U ||--o{ O : "places"
O ||--o{ OI : "contains"
O ||--o{ OSH : "has history"
OS ||--o{ OSH : "used as"
P ||--o{ OI : "in items"
P ||--o{ P_P : "has promotions"
O ||--o{ ADJ : "has adjustments"

@enduml
